#!/usr/bin/bash
set -e

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT_DIR"

mkdir -p target/classes

find src/main/java -name "*.java" > sources.txt
javac -d target/classes @sources.txt
rm sources.txt

java -cp target/classes com.scammers.Main "$@"