package codegen;

import ir.*;

public class X86Generator {
    private final StringBuilder asm = new StringBuilder();
    private StackFrame currentFrame;
    private IRFunction currentFunc;
    private final LabelManager labelManager = new LabelManager();

    public StackFrame getFrame() { return currentFrame; }
    public void appendAsm(String line) { asm.append(line).append("\n"); }
    public String getLabel(String irLabel) { return "." + currentFunc.name + "_" + irLabel; }

    public String generate(IRProgram program) {
        asm.append("; Generated by Scammer Compiler\n");
        asm.append("bits 64\n");
        asm.append("section .text\n");
        asm.append("global _start\n");
        asm.append("extern print_int, exit_program\n\n");

        asm.append("_start:\n");
        asm.append("    call main\n");
        asm.append("    mov rdi, rax\n");
        asm.append("    call exit_program\n\n");

        for (IRFunction func : program.functions.values()) {
            generateFunction(func);
        }

        return asm.toString();
    }

    private void generateFunction(IRFunction func) {
        this.currentFunc = func;
        this.currentFrame = new StackFrame();

        preprocessStack(func);

        asm.append(func.name).append(":\n");

        asm.append("    push rbp\n");
        asm.append("    mov rbp, rsp\n");
        int size = currentFrame.getPaddedSize();
        if (size > 0) asm.append("    sub rsp, ").append(size).append("\n");

        for (int i = 0; i < Math.min(func.paramNames.size(), 6); i++) {
            String pName = func.paramNames.get(i).split(" ")[1];
            asm.append("    mov qword ").append(currentFrame.getAddress(new Operand.Parameter(pName)))
                    .append(", ").append(ABI.ARG_REGISTERS[i]).append("\n");
        }

        for (BasicBlock block : func.blocks) {
            asm.append(".").append(func.name).append("_").append(block.label).append(":\n");
            for (Instruction instr : block.instructions) {
                translate(instr);
            }
        }
        asm.append("\n");
    }

    private void preprocessStack(IRFunction func) {
        for (BasicBlock b : func.blocks) {
            for (Instruction i : b.instructions) {
                if (i instanceof Instruction.BinaryOp) currentFrame.allocate(((Instruction.BinaryOp) i).dest.toString());
                if (i instanceof Instruction.UnaryOp)  currentFrame.allocate(((Instruction.UnaryOp) i).dest.toString());
                if (i instanceof Instruction.Compare)  currentFrame.allocate(((Instruction.Compare) i).dest.toString());
                if (i instanceof Instruction.Load)     currentFrame.allocate(((Instruction.Load) i).dest.toString());
                if (i instanceof Instruction.Call && ((Instruction.Call) i).dest != null)
                    currentFrame.allocate(((Instruction.Call) i).dest.toString());
            }
        }
        for (String var : func.variables.keySet()) currentFrame.allocate("[" + var + "]");
        for (String p : func.paramNames) currentFrame.allocate(p.split(" ")[1]);
    }

    private void translate(Instruction instr) {
        asm.append("    ; ").append(instr.toString()).append("\n");

        if (instr instanceof Instruction.BinaryOp) {
            handleBinary((Instruction.BinaryOp) instr);
        } else if (instr instanceof Instruction.UnaryOp) {
            Instruction.UnaryOp u = (Instruction.UnaryOp) instr;
            asm.append("    mov rax, ").append(currentFrame.getAddress(u.src)).append("\n");
            if (u.op == Instruction.UnaryOp.Op.NEG) asm.append("    neg rax\n");
            else asm.append("    not rax\n");
            asm.append("    mov ").append(currentFrame.getAddress(u.dest)).append(", rax\n");
        } else if (instr instanceof Instruction.Compare) {
            handleCompare((Instruction.Compare) instr);
        } else if (instr instanceof Instruction.Move) {
            Instruction.Move m = (Instruction.Move) instr;
            if (m.src instanceof Operand.IntLiteral || m.src instanceof Operand.BoolLiteral) {
                asm.append("    mov qword ").append(currentFrame.getAddress(m.dest))
                        .append(", ").append(currentFrame.getAddress(m.src)).append("\n");
            } else {
                asm.append("    mov rax, ").append(currentFrame.getAddress(m.src)).append("\n");
                asm.append("    mov ").append(currentFrame.getAddress(m.dest)).append(", rax\n");
            }
        } else if (instr instanceof Instruction.Store) {
            Instruction.Store s = (Instruction.Store) instr;
            if (s.src instanceof Operand.IntLiteral || s.src instanceof Operand.BoolLiteral) {
                asm.append("    mov qword ").append(currentFrame.getAddress(s.addr))
                        .append(", ").append(currentFrame.getAddress(s.src)).append("\n");
            } else {
                asm.append("    mov rax, ").append(currentFrame.getAddress(s.src)).append("\n");
                asm.append("    mov ").append(currentFrame.getAddress(s.addr)).append(", rax\n");
            }

        } else if (instr instanceof Instruction.Load) {
            Instruction.Load l = (Instruction.Load) instr;
            asm.append("    mov rax, ").append(currentFrame.getAddress(l.addr)).append("\n");
            asm.append("    mov ").append(currentFrame.getAddress(l.dest)).append(", rax\n");

        } else if (instr instanceof Instruction.JumpIf) {
            Instruction.JumpIf j = (Instruction.JumpIf) instr;
            asm.append("    mov rax, ").append(currentFrame.getAddress(j.condition)).append("\n");
            asm.append("    test rax, rax\n");
            asm.append("    jnz .").append(currentFunc.name).append("_").append(j.label).append("\n");

        } else if (instr instanceof Instruction.Jump) {
            asm.append("    jmp .").append(currentFunc.name).append("_").append(((Instruction.Jump) instr).label).append("\n");

        } else if (instr instanceof Instruction.Param) {
            Instruction.Param p = (Instruction.Param) instr;
            asm.append("    mov ").append(ABI.ARG_REGISTERS[p.index]).append(", ").append(currentFrame.getAddress(p.value)).append("\n");

        } else if (instr instanceof Instruction.Call) {
            Instruction.Call c = (Instruction.Call) instr;
            asm.append("    call ").append(c.funcName).append("\n");
            if (c.dest != null) asm.append("    mov ").append(currentFrame.getAddress(c.dest)).append(", rax\n");

        } else if (instr instanceof Instruction.Return) {
            Instruction.Return r = (Instruction.Return) instr;
            if (r.value != null) asm.append("    mov rax, ").append(currentFrame.getAddress(r.value)).append("\n");
            asm.append("    mov rsp, rbp\n");
            asm.append("    pop rbp\n");
            asm.append("    ret\n");
        }
    }

    private void handleBinary(Instruction.BinaryOp b) {
        asm.append("    mov rax, ").append(currentFrame.getAddress(b.src1)).append("\n");
        asm.append("    mov r10, ").append(currentFrame.getAddress(b.src2)).append("\n");
        switch (b.op) {
            case ADD -> asm.append("    add rax, r10\n");
            case SUB -> asm.append("    sub rax, r10\n");
            case MUL -> asm.append("    imul rax, r10\n");
            case DIV -> asm.append("    cqo\n    idiv r10\n");
            case MOD -> asm.append("    cqo\n    idiv r10\n    mov rax, rdx\n");
            case AND -> asm.append("    and rax, r10\n");
            case OR  -> asm.append("    or rax, r10\n");
        }
        asm.append("    mov ").append(currentFrame.getAddress(b.dest)).append(", rax\n");
    }
    private void handleCompare(Instruction.Compare c) {
        asm.append("    mov rax, ").append(currentFrame.getAddress(c.src1)).append("\n");
        asm.append("    cmp rax, ").append(currentFrame.getAddress(c.src2)).append("\n");
        String setInstr = switch (c.op) {
            case EQ -> "setz"; case NE -> "setnz"; case LT -> "setl";
            case LE -> "setle"; case GT -> "setg"; case GE -> "setge";
        };
        asm.append("    ").append(setInstr).append(" al\n");
        asm.append("    movzx rax, al\n");
        asm.append("    mov ").append(currentFrame.getAddress(c.dest)).append(", rax\n");
    }
}