package lexer;

public enum TokenType {
    KW_IF, KW_ELSE, KW_WHILE, KW_FOR, KW_INT, KW_FLOAT,
    KW_BOOL, KW_RETURN, KW_TRUE, KW_FALSE, KW_VOID, KW_STRUCT, KW_FN,

    IDENTIFIER,
    LIT_INT, LIT_FLOAT, LIT_STRING,

    OP_PLUS, OP_MINUS, OP_MULTIPLY, OP_DIVIDE, OP_MODULO,

    OP_EQ, OP_NEQ, OP_LT, OP_LTE, OP_GT, OP_GTE,

    OP_AND, OP_OR, OP_NOT, OP_ASSIGN,

    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,
    SEMICOLON, COLON, COMMA, DOT,

    PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN,

    EOF, ERROR
}
